junit: 4.8.2

gems:
  #- ci_reporter
  - buildr >= 1.4.6

repositories:
  remote:
   - http://repository.jboss.org/nexus/content/groups/public
   - http://guiceyfruit.googlecode.com/svn/repo/releases
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://www.ibiblio.org/maven2
   - http://download.java.net/maven/glassfish

artifacts:
  javax_inject: javax.inject:javax.inject:jar:1
  junit: junit:junit:jar:4.8.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  javax_ejb: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final


